In [1]:
import numpy as np

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [20]:
a1d = np.random.randint(10,99,50)

print(a1d)

[82 66 12 20 55 94 43 78 29 29 10 87 43 61 48 16 89 46 45 89 19 90 47 86
 93 27 23 31 17 72 35 95 97 10 70 14 58 24 54 23 18 57 80 60 21 57 55 73
 76 29]


In [17]:
len(a1d)

50

In [30]:
a1d[:5]

array([82, 66, 12, 20, 55], dtype=int32)

In [ ]:
lista_multiplos_5 = []


for n in range(len(a1d)): 
    if n%5 == 0:
        lista_multiplos_5.append(n)

print(lista_multiplos_5)


[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]


In [31]:
lista_multiplos_5 = []


for n in a1d: 
    if n%5 == 0:
        lista_multiplos_5.append(n)

print(lista_multiplos_5)


[np.int32(20), np.int32(55), np.int32(10), np.int32(45), np.int32(90), np.int32(35), np.int32(95), np.int32(10), np.int32(70), np.int32(80), np.int32(60), np.int32(55)]


- 2. Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [37]:
a2_1d = np.random.randint(1,22,30)

print(a2_1d)

[16 11 14  1 13 14  1  4 15 19 14 11  8 20  5  2 16  7 15 10  1 14 21 18
 12 12 17  3  7 20]


In [40]:
lista_impares = []


for n in a2_1d:
    if n%2 != 0:
        lista_impares.append(n)

print(lista_impares)

[np.int32(11), np.int32(1), np.int32(13), np.int32(1), np.int32(15), np.int32(19), np.int32(11), np.int32(5), np.int32(7), np.int32(15), np.int32(1), np.int32(21), np.int32(17), np.int32(3), np.int32(7)]



Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [53]:
a2d = np.random.randint(10, 100, (4,6))

print(a2d)

[[21 79 52 53 65 29]
 [57 41 74 40 30 19]
 [35 14 74 63 98 85]
 [51 55 63 10 31 37]]


In [59]:
a2d2 = np.random.rand(4,6)

print(a2d2)

[[0.20967    0.56894476 0.34607816 0.23770383 0.29055544 0.96728593]
 [0.14619678 0.66869355 0.78678161 0.40924863 0.66819406 0.77005234]
 [0.0034256  0.29703349 0.92800165 0.40183714 0.23489104 0.1284717 ]
 [0.18640954 0.22348239 0.99801833 0.61521149 0.49128698 0.42439839]]


In [60]:
np.add(a2d,a2d2)

array([[11.66113983, 74.9271754 , 11.51717014, 85.74194005, 73.32674745,
        50.07948864],
       [62.08143545,  4.9283833 , 22.90807666, 47.59553219, 54.20004089,
        34.87621001],
       [71.90929663, 97.0578121 , 86.609368  , 79.18797471, 72.73009433,
        94.29399675],
       [59.35953579, 90.81048202, 42.08101611, 77.80445348, 29.63425092,
        82.09544438]])

In [61]:
suma = np.add(a2d,a2d2)

In [62]:
np.round(suma,2)

array([[11.66, 74.93, 11.52, 85.74, 73.33, 50.08],
       [62.08,  4.93, 22.91, 47.6 , 54.2 , 34.88],
       [71.91, 97.06, 86.61, 79.19, 72.73, 94.29],
       [59.36, 90.81, 42.08, 77.8 , 29.63, 82.1 ]])

In [63]:
a2d = np.random.uniform(1, 100, (4,6)) #otra forma (mejor no usar)

print(a2d)

[[76.82328342 17.77510321 69.53277719 82.02209388 50.26802416 89.82777295]
 [77.14429196 44.75046749 64.46380457 74.29845091 98.75225019 64.11587862]
 [54.22055923 24.07338428 30.96458289  7.99853919 50.78176555 69.91095591]
 [31.32138372 18.37647154 99.09853688 68.65492411 57.36539145 79.30455343]]


Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [71]:
a3d = np.random.randint(0,2,(2,3,5))

print(a3d)

[[[0 0 0 0 1]
  [1 1 1 1 0]
  [1 1 0 1 0]]

 [[1 1 1 1 0]
  [1 1 0 1 0]
  [1 0 1 1 1]]]
